#!/bin/bash

# Tool to copy and paste dotfiles.
# Adam Heins

DOTFILES=(.zsh .zshrc
          .gitconfig .gitignore
          .vimrc .vim
          .tmux.conf
          .editrc
          .inputrc
          .dircolors
          .vimperatorrc)

# Check that dependencies are installed.
command -v rsync >/dev/null 2>&1 || { echo >&2 "rsync not installed, aborting"; exit 1; }
command -v realpath >/dev/null 2>&1 || { echo >&2 "realpath not installed, aborting"; exit 1; }

# Check that the `files' directory exists.
[ -d files ] || { echo >&2 "no dotfiles are here"; exit 1; }

# Create a directory to hold a backup of the current dotfiles on this machine.
[ -d backup ] && rm -rf backup
mkdir backup

for file in ${DOTFILES[@]}; do
  # Backup each local file.
  [ -e ~/"$file" ] && rsync -r ~/"$file" "backup"

  # Remove existing local copy (if needed) and create a symlink to the one in
  # this repo.
  if [ -e "files/$file" ]; then
    [ -e ~/"$file" ] && rm -rf ~/"$file"
    ln -s $(realpath "files/$file") ~/"$file"
  fi
done

# Create vim aliases symlink.
ln -s ~/.vim/aliases.vim ~/.vim/after/plugin/aliases.vim
